single button control
eg321/esp32-motorized-roller-blinds pull request #16
Opened 2022-06-29 11:28 UTC by Antikillerbm

2022-07-04 07:39 UTC, eg321 requested changes

2022-07-04 07:39 UTC, eg321 commented on README.md
> +Button control modified to use only one button per 1 blind
you're rewriting this file instead of adding info about new possibilities. You shouldn't remove information about already implemented features.

2022-07-04 07:39 UTC, eg321 commented on src/main.cpp
> +#define SINGLE_BUTTON_CONTROL   // If you use only one button to move Up/Down
Don't make this mode as default please. Anyone who already use this codebase shouldn't broke their installations after your changes.
So, who wants "single button control" can enable this option (at platformio env for example), all other - will keep current settings.

2022-07-04 07:39 UTC, eg321 commented on src/main.cpp
> +#ifdef SINGLE_BUTTON_CONTROL
you can use `ifndef`, if you want to check for "if not defined".

2022-07-04 07:39 UTC, eg321 commented on src/main.cpp
> +
let's move this into separate method like `singleButtonReleaseHandler`

2022-07-21 17:40 UTC, closed without merging

2022-07-21 17:44 UTC, Antikillerbm commented
Added BH1750 light sensor
All added features are disabled by default

2022-07-26 07:32 UTC, eg321 commented
@Antikillerbm it looks like you've commited new separate feature into this branch also. It's not a good workflow.
If you really want to contribute into project this new feature, please create separate pull request.

2022-07-26 07:34 UTC, Antikillerbm commented
Блин, я не очень понимаю как это в гите все работает. 
Я вообще не программист((
Я могу скинуь код файлом и удалить свой форк нафик.

2022-08-05 08:51 UTC, eg321 commented
В целом, есть много инструкций как и чего, тут в двух словах я точно не смогу обучить. Если есть желание - всё это можно найти на ютубе или в других местах. 

К сожалению, у меня пока нет ресурсов, чтобы реализовывать такой функционал, но я могу его принимать в виде реквестов и помогать советами, ревьювить код. Код, который не удовлетворяет правилам организации кода и проекта, я принять не могу.